import json
import os
import platform
import sys
from datetime import datetime
from html import escape

# ── Windows GTK DLL path setup (required for WeasyPrint) ─────────────────────
# Python 3.8+ on Windows no longer searches PATH for DLLs. We must explicitly
# register the MSYS2 ucrt64 bin directory so WeasyPrint can find Pango/GLib.
if sys.platform == 'win32':
    _sys_drive = os.environ.get('SYSTEMDRIVE', 'C:')
    _gtk_path = os.path.join(_sys_drive + os.sep, 'msys64', 'ucrt64', 'bin')
    if os.path.isdir(_gtk_path):
        os.add_dll_directory(_gtk_path)


# ── Report ID Counter ─────────────────────────────────────────────────────────

def _get_next_report_id():
    """
    Auto-generate a sequential report ID like DFL-2026-0001.
    Tracked via a JSON counter file in the project root.
    """
    counter_path = os.path.join(os.path.dirname(os.path.dirname(__file__)),
                                'report_counter.json')
    counter = 0
    if os.path.exists(counter_path):
        try:
            with open(counter_path, 'r') as f:
                data = json.load(f)
                counter = data.get('count', 0)
        except (json.JSONDecodeError, IOError):
            counter = 0

    counter += 1
    with open(counter_path, 'w') as f:
        json.dump({'count': counter}, f)

    year = datetime.now().strftime('%Y')
    return f"DFL-{year}-{counter:04d}"


# ── HTML Template Helpers ─────────────────────────────────────────────────────

def _esc(text, maxlen=0):
    """Escape HTML and optionally truncate."""
    text = str(text) if text else '\u2014'
    if maxlen and len(text) > maxlen:
        text = text[:maxlen] + '\u2026'
    return escape(text)


def _severity_html(level):
    """Return an HTML span with the appropriate severity class."""
    level_upper = str(level).upper()
    if level_upper in ('CRITICAL', 'HIGH'):
        return f'<span class="sev-high">{level_upper}</span>'
    elif level_upper in ('MEDIUM',):
        return f'<span class="sev-med">{level_upper}</span>'
    elif level_upper in ('LOW', 'INFO'):
        return f'<span class="sev-low">{level_upper}</span>'
    return escape(level_upper)


# ── CSS ───────────────────────────────────────────────────────────────────────

REPORT_CSS = """
@page {
    size: A4;
    margin: 25mm 20mm 25mm 20mm;

    /* Header */
    @top-left { content: ""; border-bottom: 2px solid #8b0000; width: 10%; }
    @top-center {
        content: "CONFIDENTIAL // RESTRICTED DISTRIBUTION // AUTHORIZED PERSONNEL ONLY";
        color: #8b0000; font-size: 9pt; font-weight: bold; font-family: Arial, sans-serif;
        letter-spacing: 1px; border-bottom: 2px solid #8b0000; width: 80%;
        text-align: center; padding-bottom: 5px; vertical-align: bottom; white-space: nowrap;
    }
    @top-right { content: ""; border-bottom: 2px solid #8b0000; width: 10%; }

    /* Footer */
    @bottom-left {
        content: "Generated by: TriageHound v1.0"; font-size: 8pt;
        font-family: 'Courier New', Courier, monospace;
        color: #333; white-space: nowrap; border-top: 2px solid #8b0000; width: 30%;
        text-align: left; vertical-align: top; padding-top: 8px;
    }
    @bottom-center {
        content: ""; border-top: 2px solid #8b0000; width: 40%;
        vertical-align: top; padding-top: 8px;
    }
    @bottom-right {
        content: "Page " counter(page); font-size: 9pt; font-family: Arial, sans-serif;
        color: #000; white-space: nowrap; border-top: 2px solid #8b0000; width: 30%;
        text-align: right; vertical-align: top; padding-top: 8px;
    }
}

body {
    font-family: 'Times New Roman', Times, serif;
    color: #000; margin: 0; padding: 0; font-size: 10pt;
}
*, *::before, *::after { box-sizing: border-box; }

/* Cover Page */
.cover-page { min-height: 230mm; position: relative; }
.header-table {
    width: 100%; border-bottom: 4px double #000;
    padding-bottom: 15px; margin-bottom: 30px;
}
.institute-name {
    font-size: 22pt; font-family: Arial, sans-serif;
    font-weight: 900; text-transform: uppercase; margin: 0; line-height: 1;
}
.institute-sub {
    font-size: 11pt; font-family: Arial, sans-serif;
    letter-spacing: 2px; color: #444; margin-top: 5px;
}
.doc-control {
    border: 1px solid #000; padding: 8px;
    font-family: 'Courier New', Courier, monospace;
    font-size: 9pt; text-align: left; background-color: #f9f9f9;
}
.doc-control td { padding: 2px 5px; }

.report-title-container { text-align: center; margin: 50px 0; }
.report-title-container h1 {
    font-size: 26pt; margin: 0; text-transform: uppercase;
    font-family: Arial, sans-serif; letter-spacing: 1px;
}
.report-title-container h2 {
    font-size: 14pt; font-weight: normal; margin: 10px 0 0 0; color: #333;
}

table.case-info {
    width: 100%; border-collapse: collapse;
    border: 2px solid #000; margin-bottom: 40px;
}
table.case-info th, table.case-info td {
    border: 1px solid #000; padding: 10px 15px; font-size: 12pt;
}
table.case-info th {
    width: 30%; background-color: #f2f2f2; text-align: left;
    text-transform: uppercase; font-family: Arial, sans-serif;
    font-size: 10pt; font-weight: bold;
}
table.case-info td {
    font-family: 'Courier New', Courier, monospace; font-weight: bold;
}

.attestation {
    border: 1px solid #000; padding: 20px; font-size: 11pt;
    line-height: 1.5; background-color: #fbfbfb; text-align: justify;
}
.signature-block {
    margin-top: 40px; display: table; width: 100%;
}
.signature-line {
    display: table-cell; width: 45%; border-top: 1px solid #000;
    padding-top: 5px; text-align: center;
    font-family: Arial, sans-serif; font-size: 10pt;
}
.signature-spacer { display: table-cell; width: 10%; }

/* General Content Styles */
.content-section { padding-top: 10mm; page-break-before: always; }
h2.section-heading {
    font-size: 14pt; font-family: Arial, sans-serif;
    text-transform: uppercase; border-bottom: 2px solid #000;
    padding-bottom: 5px; margin-top: 0; margin-bottom: 15px;
}

/* Data Tables */
.data-table {
    width: 100%; border-collapse: collapse;
    margin-bottom: 25px; border: 1px solid #000;
}
.data-table th, .data-table td {
    border: 1px solid #000; padding: 6px 8px;
    font-size: 9pt; page-break-inside: avoid;
}
.data-table th {
    background-color: #f2f2f2; font-family: Arial, sans-serif;
    text-transform: uppercase; text-align: left;
    font-size: 8.5pt; font-weight: bold;
}
.data-table td {
    font-family: 'Courier New', Courier, monospace; word-break: break-all;
}

.metrics-grid {
    width: 100%; border-collapse: collapse;
    margin-bottom: 25px; border: 2px solid #000;
}
.metrics-grid th, .metrics-grid td {
    border: 1px solid #000; text-align: center; padding: 12px;
}
.metrics-grid th {
    background-color: #f2f2f2; font-family: Arial, sans-serif;
    font-size: 8pt; text-transform: uppercase;
}
.metrics-grid td {
    font-size: 20pt; font-weight: bold;
    font-family: 'Courier New', Courier, monospace;
}

.sev-high {
    background-color: #8b0000; color: #fff; padding: 2px 6px;
    font-family: Arial, sans-serif; font-weight: bold; font-size: 8pt;
}
.sev-med {
    background-color: #d2691e; color: #fff; padding: 2px 6px;
    font-family: Arial, sans-serif; font-weight: bold; font-size: 8pt;
}
.sev-low {
    background-color: #2e8b57; color: #fff; padding: 2px 6px;
    font-family: Arial, sans-serif; font-weight: bold; font-size: 8pt;
}
"""


# ── HTML Section Builders ─────────────────────────────────────────────────────

def _build_cover_page(case_info, report_id, now_str):
    """Build the cover page HTML."""
    case_id = _esc(case_info.get('case_id', '\u2014'))
    case_name = _esc(case_info.get('case_name', 'Forensic Investigation'))
    investigator = _esc(case_info.get('investigator_name', '\u2014'))
    target = _esc(case_info.get('target_system', '\u2014'))
    os_platform = f"{platform.system()} {platform.release()}"
    issued_date = datetime.now().strftime('%Y-%m-%d')

    return f"""
    <div class="cover-page">
        <table class="header-table">
            <tr>
                <td style="width: 60%;">
                    <div class="institute-name">Digital Forensics Lab</div>
                    <div class="institute-sub">DEPARTMENT OF CYBER INVESTIGATIONS</div>
                </td>
                <td style="width: 40%; text-align: right;">
                    <table class="doc-control" style="float: right;">
                        <tr><td><strong>REPORT ID:</strong></td><td>{_esc(report_id)}</td></tr>
                        <tr><td><strong>CASE REF:</strong></td><td>{case_id}</td></tr>
                        <tr><td><strong>ISSUED:</strong></td><td>{issued_date}</td></tr>
                    </table>
                </td>
            </tr>
        </table>

        <div class="report-title-container">
            <h1>Forensic Investigation Report</h1>
            <h2>OFFICIAL RECORD OF FINDINGS</h2>
        </div>

        <table class="case-info">
            <tr><th>Case Name</th><td>{case_name}</td></tr>
            <tr><th>Lead Investigator</th><td>{investigator}</td></tr>
            <tr><th>Target System / Hostname</th><td>{target}</td></tr>
            <tr><th>Operating System Platform</th><td>{_esc(os_platform)}</td></tr>
            <tr><th>Collection Timestamp</th><td>{_esc(now_str)}</td></tr>
            <tr><th>Diagnostic Engine</th><td>TriageHound v1.0</td></tr>
        </table>

        <div class="attestation">
            <strong>INVESTIGATOR'S ATTESTATION:</strong><br><br>
            I, the undersigned lead investigator, hereby certify that the digital forensic
            analysis described within this report was conducted in a secure laboratory
            environment. The data extraction, preservation, and analysis procedures utilized
            adhere strictly to standard operating protocols for digital evidence handling.
            The findings presented in this document represent a true and accurate reflection
            of the artifacts acquired from the target system at the specified collection timestamp.
            <div class="signature-block">
                <div class="signature-line">
                    <br><strong>{investigator}</strong><br>Lead Digital Forensics Investigator
                </div>
                <div class="signature-spacer"></div>
                <div class="signature-line">
                    <br><strong>Date / Signature</strong><br>Lab Director Authorization
                </div>
            </div>
        </div>
    </div>
    """


def _build_summary_page(counts, yara_rows, sigma_rows):
    """Build the Executive Summary + Breakdown page."""
    total_artifacts = sum(counts.values()) if counts else 0
    yara_count = len(yara_rows)
    sigma_count = len(sigma_rows)
    categories = len([v for v in counts.values() if v > 0]) if counts else 0

    # Threat assessment rows
    threat_rows = ''
    for row in yara_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        sev = raw.get('severity', 'MEDIUM').upper()
        rule = _esc(raw.get('rule', '\u2014'), 40)
        target_file = _esc(os.path.basename(raw.get('filepath', '\u2014')), 50)
        threat_rows += f"""
            <tr>
                <td>{_severity_html(sev)}</td>
                <td>{rule}</td>
                <td>{target_file}</td>
            </tr>"""

    for row in sigma_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        level = raw.get('rule_level', 'medium').upper()
        rule_title = _esc(raw.get('rule_title', '\u2014'), 40)
        threat_rows += f"""
            <tr>
                <td>{_severity_html(level)}</td>
                <td>{rule_title}</td>
                <td>Sigma Behavioral Detection</td>
            </tr>"""

    if not threat_rows:
        threat_rows = """
            <tr>
                <td colspan="3" style="text-align: center; color: #2e8b57; font-family: Arial, sans-serif;">
                    No threats detected \u2014 all checks passed.
                </td>
            </tr>"""

    # Evidence breakdown
    type_map = [
        ('Processes',        counts.get('process', 0),        'psutil'),
        ('Recent Files',     counts.get('recent_file', 0),    'Registry'),
        ('Startup Programs', counts.get('startup_entry', 0),  'Registry + Folders'),
        ('USB Devices',      counts.get('usb_device', 0),     'Registry'),
        ('Browser History',  counts.get('browser_history', 0),'Chrome / Edge / Firefox'),
        ('Event Logs',       counts.get('event_log', 0),      'EVTX Parser'),
        ('Prefetch',         counts.get('prefetch', 0),       'Prefetch Parser'),
        ('ShimCache',        counts.get('shimcache', 0),      'Registry (SYSTEM)'),
        ('USN Journal',      counts.get('usn_journal', 0),    'NTFS Raw I/O'),
        ('YARA Hits',        counts.get('yara_match', 0),     'YARA Scanner'),
        ('Sigma Alerts',     counts.get('sigma_alert', 0),    'Sigma Engine'),
        ('Virus Total',      counts.get('virustotal', 0),     'VirusTotal API'),
        ('Shadow Copies',    counts.get('vss', 0),            'VSS Extractor'),
    ]
    breakdown_rows = ''
    for label, count, source in type_map:
        breakdown_rows += f"""
            <tr><td>{_esc(label)}</td><td>{count}</td><td>{_esc(source)}</td></tr>"""

    return f"""
    <div class="content-section">
        <h2 class="section-heading">1.0 Executive Detections Summary</h2>
        <table class="metrics-grid">
            <tr>
                <th>Evidence Items Analyzed</th>
                <th>YARA Rule Hits</th>
                <th>Detection Categories</th>
                <th>Sigma Alerts Triggered</th>
            </tr>
            <tr>
                <td>{total_artifacts}</td>
                <td>{yara_count}</td>
                <td>{categories}</td>
                <td>{sigma_count}</td>
            </tr>
        </table>

        <h2 class="section-heading">2.0 Threat Assessment &amp; Alerts</h2>
        <table class="data-table">
            <tr>
                <th style="width: 15%;">Severity</th>
                <th style="width: 35%;">Detection Rule Matched</th>
                <th style="width: 50%;">Target File / Artifact</th>
            </tr>
            {threat_rows}
        </table>

        <h2 class="section-heading">3.0 Evidence Breakdown Matrix</h2>
        <table class="data-table">
            <tr>
                <th style="width: 33%;">Artifact Type</th>
                <th style="width: 33%;">Artifact Count</th>
                <th style="width: 34%;">Source Module</th>
            </tr>
            {breakdown_rows}
        </table>
    </div>
    """


def _build_yara_section(yara_rows):
    """Build YARA Malware Hits section."""
    if not yara_rows:
        return ''

    rows_html = ''
    for row in yara_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('rule', '\u2014'), 30)}</td>
                <td>{_severity_html(raw.get('severity', '\u2014'))}</td>
                <td>{_esc(os.path.basename(raw.get('filepath', '\u2014')), 30)}</td>
                <td>{_esc(raw.get('description', '\u2014'), 50)}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">4.0 YARA Malware Hits</h2>
        <table class="data-table">
            <tr>
                <th style="width: 30%;">Rule Matched</th>
                <th style="width: 10%;">Severity</th>
                <th style="width: 25%;">Target File</th>
                <th style="width: 35%;">Description</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_startup_section(startup_rows):
    """Build Startup Programs section."""
    if not startup_rows:
        return ''

    rows_html = ''
    for row in startup_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        is_sus = raw.get('flagged_suspicious', False)
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('name', '\u2014'), 25)}</td>
                <td>{_esc(raw.get('command', '\u2014'), 50)}</td>
                <td>{_esc(raw.get('source_type', '\u2014'))}</td>
                <td>{'<span class="sev-high">YES</span>' if is_sus else 'No'}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">5.0 Startup Programs (Autoruns)</h2>
        <table class="data-table">
            <tr>
                <th style="width: 20%;">Name</th>
                <th style="width: 50%;">Command Path</th>
                <th style="width: 20%;">Source</th>
                <th style="width: 10%;">Suspicious</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_usb_section(usb_rows):
    """Build USB Device History section."""
    if not usb_rows:
        return ''

    rows_html = ''
    for row in usb_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('friendly_name', '\u2014'), 40)}</td>
                <td>{_esc(raw.get('serial_number', '\u2014'), 30)}</td>
                <td>{_esc(raw.get('device_id', 'N/A'), 40)}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">6.0 USB Device History</h2>
        <table class="data-table">
            <tr>
                <th style="width: 40%;">Device Name</th>
                <th style="width: 30%;">Serial Number</th>
                <th style="width: 30%;">Device ID</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_processes_section(process_rows):
    """Build Running Processes section."""
    if not process_rows:
        return ''

    rows_html = ''
    for row in process_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        mem_rss = raw.get('memory_rss')
        mem_mb = str(round(mem_rss / (1024 * 1024), 1)) if mem_rss else '\u2014'
        cpu = str(raw.get('cpu_percent', '\u2014'))
        username = _esc(raw.get('username', '\u2014'), 25)
        rows_html += f"""
            <tr>
                <td>{raw.get('pid', '\u2014')}</td>
                <td>{_esc(raw.get('name', '\u2014'), 35)}</td>
                <td>{cpu}</td>
                <td>{mem_mb}</td>
                <td>{username}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">7.0 Running Processes Snapshot (All {len(process_rows)})</h2>
        <table class="data-table">
            <tr>
                <th>PID</th>
                <th>Process Name</th>
                <th>CPU %</th>
                <th>Memory (MB)</th>
                <th>Username</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_recent_files_section(recent_rows):
    """Build Recently Accessed Files section."""
    if not recent_rows:
        return ''

    rows_html = ''
    for row in recent_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('filename', '\u2014'), 30)}</td>
                <td>{_esc(raw.get('filepath', raw.get('path', 'Registry Entry')), 70)}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">8.0 Recently Accessed Files (All {len(recent_rows)})</h2>
        <table class="data-table">
            <tr>
                <th style="width: 30%;">Filename Fragment</th>
                <th style="width: 70%;">Registry Reference / Full Path</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_shimcache_section(shimcache_rows):
    """Build ShimCache section."""
    if not shimcache_rows:
        return ''

    rows_html = ''
    for row in shimcache_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        rows_html += f"""
            <tr>
                <td>{raw.get('cache_position', '\u2014')}</td>
                <td>{_esc(raw.get('executable_path', '\u2014'), 65)}</td>
                <td>{_esc(raw.get('last_modified', '\u2014'), 25)}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">9.0 Application Compatibility Cache (ShimCache) (All {len(shimcache_rows)})</h2>
        <table class="data-table">
            <tr>
                <th style="width: 10%;">#</th>
                <th style="width: 60%;">Executable Path</th>
                <th style="width: 30%;">Last Modified</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_timeline_section(timeline_data):
    """Build Chronological Event Timeline section."""
    if not timeline_data:
        return ''

    rows_html = ''
    for e in timeline_data:
        rows_html += f"""
            <tr>
                <td>{_esc(str(e.get('time', '\u2014')), 25)}</td>
                <td>{_esc(str(e.get('type', '\u2014')), 18)}</td>
                <td>{_esc(str(e.get('source', '\u2014')), 18)}</td>
                <td>{_esc(str(e.get('event', '\u2014')), 55)}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">10.0 Chronological Event Timeline (All {len(timeline_data)})</h2>
        <table class="data-table">
            <tr>
                <th style="width: 25%;">Timestamp</th>
                <th style="width: 15%;">Type</th>
                <th style="width: 15%;">Source</th>
                <th style="width: 45%;">Event Description</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_browser_section(browser_rows):
    """Build Browser History section."""
    if not browser_rows:
        return ''

    rows_html = ''
    for row in browser_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('browser', '\u2014'))}</td>
                <td>{_esc(raw.get('title', '\u2014'), 30)}</td>
                <td>{_esc(raw.get('url', '\u2014'), 50)}</td>
                <td>{_esc(raw.get('last_visited', '\u2014'), 22)}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">11.0 Browser History (All {len(browser_rows)})</h2>
        <table class="data-table">
            <tr>
                <th style="width: 15%;">Browser</th>
                <th style="width: 25%;">Title</th>
                <th style="width: 40%;">URL</th>
                <th style="width: 20%;">Last Visited</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_prefetch_section(prefetch_rows):
    """Build Prefetch section."""
    if not prefetch_rows:
        return ''

    rows_html = ''
    for row in prefetch_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('executable_name', '\u2014'), 35)}</td>
                <td>{raw.get('run_count', '\u2014')}</td>
                <td>{_esc(raw.get('last_run', '\u2014'), 22)}</td>
                <td>{_esc(raw.get('pf_filename', '\u2014'), 30)}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">12.0 Prefetch \u2014 Execution Evidence</h2>
        <table class="data-table">
            <tr>
                <th style="width: 30%;">Executable</th>
                <th style="width: 15%;">Run Count</th>
                <th style="width: 25%;">Last Run</th>
                <th style="width: 30%;">Prefetch File</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_usn_section(usn_rows):
    """Build USN Journal section."""
    if not usn_rows:
        return ''

    rows_html = ''
    for row in usn_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('timestamp', '\u2014'), 22)}</td>
                <td>{_esc(raw.get('filename', '\u2014'), 35)}</td>
                <td>{_esc(raw.get('reason_summary', '\u2014'), 35)}</td>
                <td>{'Yes' if raw.get('is_directory') else 'No'}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">13.0 USN Journal \u2014 File System Changes (All {len(usn_rows)})</h2>
        <table class="data-table">
            <tr>
                <th style="width: 25%;">Timestamp</th>
                <th style="width: 30%;">Filename</th>
                <th style="width: 30%;">Reason</th>
                <th style="width: 15%;">Dir</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_sigma_section(sigma_rows):
    """Build Sigma Alerts section."""
    if not sigma_rows:
        return ''

    rows_html = ''
    for row in sigma_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        matched = raw.get('matched_event', {})
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('rule_title', '\u2014'), 35)}</td>
                <td>{_severity_html(raw.get('rule_level', '\u2014'))}</td>
                <td>{matched.get('event_id', '\u2014')}</td>
                <td>{_esc(matched.get('timestamp', '\u2014'), 22)}</td>
                <td>{_esc(raw.get('sigma_file', '\u2014'), 25)}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">14.0 Sigma Alerts \u2014 Behavioral Detections</h2>
        <table class="data-table">
            <tr>
                <th style="width: 30%;">Rule</th>
                <th style="width: 12%;">Level</th>
                <th style="width: 10%;">Event ID</th>
                <th style="width: 23%;">Timestamp</th>
                <th style="width: 25%;">Rule File</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_vt_section(vt_rows):
    """Build VirusTotal section."""
    if not vt_rows:
        return ''

    rows_html = ''
    for row in vt_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        is_mal = raw.get('is_malicious')
        status = '<span class="sev-high">MALICIOUS</span>' if is_mal else 'Clean'
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('label', raw.get('meaningful_name', '\u2014')), 30)}</td>
                <td>{_esc(raw.get('detection_ratio', '\u2014'))}</td>
                <td>{_esc(raw.get('threat_label', '\u2014'), 30)}</td>
                <td>{status}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">15.0 VirusTotal \u2014 Hash Reputation</h2>
        <table class="data-table">
            <tr>
                <th style="width: 30%;">File</th>
                <th style="width: 20%;">Detection Ratio</th>
                <th style="width: 25%;">Threat Label</th>
                <th style="width: 25%;">Status</th>
            </tr>
            {rows_html}
        </table>
    """


def _build_vss_section(vss_rows):
    """Build Volume Shadow Copies section."""
    if not vss_rows:
        return ''

    rows_html = ''
    for row in vss_rows:
        raw = json.loads(row.get('raw_data', '{}'))
        artifacts = raw.get('artifacts_found', [])
        artifact_names = ', '.join(
            [a.get('artifact_type', '') for a in artifacts[:5]]) if artifacts else 'None'
        rows_html += f"""
            <tr>
                <td>{_esc(raw.get('shadow_id', '\u2014'), 40)}</td>
                <td>{_esc(raw.get('creation_time', '\u2014'), 25)}</td>
                <td>{_esc(artifact_names, 40)}</td>
            </tr>"""

    return f"""
        <h2 class="section-heading">16.0 Volume Shadow Copies</h2>
        <table class="data-table">
            <tr>
                <th style="width: 40%;">Shadow Copy</th>
                <th style="width: 30%;">Creation Time</th>
                <th style="width: 30%;">Artifacts Found</th>
            </tr>
            {rows_html}
        </table>
    """


# ── Main Report Function ─────────────────────────────────────────────────────

def generate_pdf_report(case_info, timeline_data, output_path, db_manager=None):
    """
    Generate a professional official forensic investigation PDF report.

    Uses WeasyPrint to convert a structured HTML document to PDF with
    proper @page headers/footers, cover page, attestation, and all
    evidence sections.

    Args:
        case_info:     dict with case_id, case_name, investigator_name, target_system
        timeline_data: list of timeline event dicts (for the timeline section)
        output_path:   where to write the PDF
        db_manager:    DBManager instance \u2014 if provided, enables per-type sections
    """
    from weasyprint import HTML  # type: ignore[import-untyped]

    now_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')
    case_id = case_info.get('case_id', 'UNKNOWN')
    report_id = _get_next_report_id()

    # Pull per-type evidence if db_manager available
    counts = {}
    yara_rows = []
    startup_rows = []
    process_rows = []
    browser_rows = []
    usb_rows = []
    recent_rows = []
    prefetch_rows = []
    usn_rows = []
    shimcache_rows = []
    sigma_rows = []
    vt_rows = []
    vss_rows = []

    if db_manager:
        counts = db_manager.get_artifact_counts(case_id)
        yara_rows     = db_manager.get_evidence_by_type(case_id, 'yara_match')
        startup_rows  = db_manager.get_evidence_by_type(case_id, 'startup_entry')
        process_rows  = db_manager.get_evidence_by_type(case_id, 'process')
        browser_rows  = db_manager.get_evidence_by_type(case_id, 'browser_history')
        usb_rows      = db_manager.get_evidence_by_type(case_id, 'usb_device')
        recent_rows   = db_manager.get_evidence_by_type(case_id, 'recent_file')
        prefetch_rows = db_manager.get_evidence_by_type(case_id, 'prefetch')
        usn_rows      = db_manager.get_evidence_by_type(case_id, 'usn_journal')
        shimcache_rows = db_manager.get_evidence_by_type(case_id, 'shimcache')
        sigma_rows    = db_manager.get_evidence_by_type(case_id, 'sigma_alert')
        vt_rows       = db_manager.get_evidence_by_type(case_id, 'virustotal')
        vss_rows      = db_manager.get_evidence_by_type(case_id, 'vss')

    # ── Build the full HTML document ──────────────────────────────────────────

    # YARA + Startup + USB grouped together (page 3)
    page3_sections = ''
    page3_sections += _build_yara_section(yara_rows)
    page3_sections += _build_startup_section(startup_rows)
    page3_sections += _build_usb_section(usb_rows)

    # Processes + Recent Files (page 4)
    page4_sections = ''
    page4_sections += _build_processes_section(process_rows)
    page4_sections += _build_recent_files_section(recent_rows)

    # ShimCache + Timeline (page 5)
    page5_sections = ''
    page5_sections += _build_shimcache_section(shimcache_rows)
    page5_sections += _build_timeline_section(timeline_data)

    # Additional sections on separate pages
    extra_sections = ''
    extra_sections += _build_browser_section(browser_rows)
    extra_sections += _build_prefetch_section(prefetch_rows)
    extra_sections += _build_usn_section(usn_rows)
    extra_sections += _build_sigma_section(sigma_rows)
    extra_sections += _build_vt_section(vt_rows)
    extra_sections += _build_vss_section(vss_rows)

    # Build page 3 content (only if there's data)
    page3_html = ''
    if page3_sections.strip():
        page3_html = f'<div class="content-section">{page3_sections}</div>'

    # Build page 4 content
    page4_html = ''
    if page4_sections.strip():
        page4_html = f'<div class="content-section">{page4_sections}</div>'

    # Build page 5 content
    page5_html = ''
    if page5_sections.strip():
        page5_html = f'<div class="content-section">{page5_sections}</div>'

    # Build extra pages
    extra_html = ''
    if extra_sections.strip():
        extra_html = f'<div class="content-section">{extra_sections}</div>'

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Official Forensic Report \u2014 {_esc(case_id)}</title>
    <style>
{REPORT_CSS}
    </style>
</head>
<body>

    <!-- COVER PAGE -->
    {_build_cover_page(case_info, report_id, now_str)}

    <!-- PAGE 2: SUMMARY & BREAKDOWN -->
    {_build_summary_page(counts, yara_rows, sigma_rows)}

    <!-- PAGE 3: YARA, STARTUP, USB -->
    {page3_html}

    <!-- PAGE 4: PROCESSES & RECENT FILES -->
    {page4_html}

    <!-- PAGE 5: SHIMCACHE & TIMELINE -->
    {page5_html}

    <!-- ADDITIONAL SECTIONS -->
    {extra_html}

</body>
</html>"""

    # ── Convert to PDF ────────────────────────────────────────────────────────
    HTML(string=html_content).write_pdf(output_path)
